pub mod add_class;
pub mod add_course;
pub mod download_submitted_assignments;
pub mod get_classes;
pub mod get_course_detail;
pub mod register_scores;
pub mod search_courses;
pub mod set_course_status;
pub mod submit_assignment;
