[package]
name = "isucholar-core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx.workspace = true
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
num-traits.workspace = true
futures.workspace = true
