[workspace]
members = ["isucholar-core", "isucholar"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
sqlx = { version = "0.5", default-features = false, features = ["macros", "runtime-actix-rustls", "mysql", "chrono", "decimal"] }
serde = { version = "1", features = ["derive"] }
async-trait = { version = "0.1" }
anyhow = { version = "1" }
thiserror = { version = "1" }
