[workspace]
members = ["core", "infra", "http-core", "http-app"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
sqlx = { version = "0.5", default-features = false, features = ["macros", "runtime-actix-rustls", "mysql", "chrono", "decimal"] }
serde = { version = "1", features = ["derive"] }
async-trait = { version = "0.1" }
anyhow = { version = "1" }
thiserror = { version = "1" }
num-traits = { version = "0.2" }
futures = "0.3"
tokio = { version = "1", features = ["fs", "process", "macros"] }
serde_json = "1.0.96"
