version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: isucon11-final-myql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: isucholar-test
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      TZ: 'Asia/Tokyo'
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
