pub mod announcement_repository;
pub mod class_repository;
pub mod course_repository;
pub mod error;
pub mod registration_course_repository;
pub mod registration_repository;
pub mod submission_repository;
pub mod unread_announcement_repository;
pub mod user_repository;
